### ISSUE TITLE
Craft 5

### ISSUE THREAD

**Issue by idleog** [nystudio107/craft-connect#47]
### Question
Is this plugin compatible with Craft5 ?

cheers, Peter

**Comment by khalwat** [comment]
Not yet, no. It's on the list tho!

**Comment by hcaandersen** [comment]
Is it possible to get a progress update on this? This plug-in is the only thing preventing us from upgrading to Craft5.

**Comment by khalwat** [comment]
Should be done shortly, within the next month or so. It should be a very straightforward port.

**Comment by hcaandersen** [comment]
That's brilliant! Thank you very much!

**Comment by khalwat** [comment]
After looking into porting this plugin to Craft 5, I decided to end up deprecating it.

But it's not because I didn't want to port it, it's because it's not needed.

The functionality this plugin provides is entirely possible to do with native Craft, without the need for this plugin at all.

I wrote a whole article on the subject (which probably took longer to do than the port would have, ironically):

[Connecting to an External Database in Craft CMS](https://nystudio107.com/blog/connecting-to-an-external-database-in-craft-cms)

Let me know if you have any questions, I'm happy to help @hcaandersen
